name: Java Associativity Test

# Ce workflow se déclenche lorsque du code est poussé sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Vérifier et cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2: Construire l'image Docker à partir du Dockerfile
    - name: Build Docker image
      run: docker build -t associativity-test .

    # Étape 3: Exécuter le conteneur Docker
    - name: Run Docker container
      run: docker run associativity-test

    # Étape 4: Lire et afficher le fichier résultat `answer_associativity.txt`
    - name: Show results
      run: cat answer_associativity.txt

    # Optionnel : pousser les résultats sur le dépôt
    - name: Push results to repo
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add answer_associativity.txt
        git commit -m "Update result"
        git push
